apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
     app.kubernetes.io/name: mysql
     app.kubernetes.io/part-of: anakonda
     app.kubernetes.io/project: anakonda
     app.kubernetes.io/env: test 
     
spec:
   type: ClusterIP
   clusterIP: None
   selector:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: anakonda
      app.kubernetes.io/project: anakonda
      app.kubernetes.io/env: test 
   ports:
     - name: mysql
       port: 3306
